[sources.rails_logs]
type = "kafka"
bootstrap_servers = "broker:9092"
group_id = "consumer-group-name"
topics = ["rails-log"]

[sinks.loki]
type = "loki"
inputs = [ "rails_logs" ]
endpoint = "http://loki-write:3100"
tenant_id = "tenant1"
encoding.codec = "json"
labels.job = "{{ source_type }}"

[sinks.console]
inputs = ["rails_logs"]
target = "stdout"
type = "console"
encoding.codec = "json"


[sources.rails_logs]
type              = "kafka"
bootstrap_servers = "broker:9092"
group_id          = "consumer-group-name"
topics            = ["rails-log"]


[transforms.modified_logs]
type = "remap"
inputs = ["rails_logs"]
source = '''
  .id = to_int(now())
  .event_time = to_unix_timestamp(now())
  .body = "Some rails logs"
'''

source = ". |= parse_json!(.message)"

[sinks.loki]
type              = "loki"
inputs            = [ "modified_logs" ]
endpoint          = "http://loki:3100"
encoding.codec    = "json"
labels.service    = "rails-logs"
