[sources.logs]
type = "kafka"
bootstrap_servers = "broker:9092"
group_id = "consumer-group-name"
topics = ["rails-log"]


[sinks.console]
inputs = ["logs"]
target = "stdout"
type = "console"
encoding.codec = "json"
